services:
  # Backend Service (sẽ serve cả frontend)
  - type: web
    name: quiz-app-backend
    env: node
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # Link to Render secret file or manually add
      - key: ADMIN_KEY
        sync: false # Link to Render secret file or manually add
      - key: FRONTEND_URL
        value: https://quiz-app-backend.onrender.com # Same as backend URL